# Cognito
COGNITO_CLIENT_ID: !Ref UserPoolClient
COGNITO_CLIENT_SECRET: !GetAtt UserPoolClient.ClientSecret

# Database
MAIN_TABLE_NAME: !Ref MainTable

# Bucket
PRODUCTS_BUCKET: !Ref ProductsBucket

#CDNs
PRODUCTS_CDN_DOMAIN_NAME: !If
  - ShouldSetupProductsCdnCustomDomain
  - ${env:PRODUCTS_CDN_DOMAIN_NAME, ''}
  - !GetAtt ProductsBucketCDN.DomainName

#Queues
ORDERS_QUEUE: !Ref OrdersQueue
